### ISSUE TITLE
errors evaluating incorrect expressions (notice)

### ISSUE THREAD

**Issue by zelig** [ethereum/natspec.js#1]
If method supplied is not known to the contract, then the output is the somewhat misleading error message: "Natspec evaluation failed, wrong input params".

``` javascript
var natspec = require('natspec');

var natspecExpression = "Will multiply `a` by 7 and return `a * 7`.";
var call = {
    method: 'missing_method',
    abi: abi,
    transaction: transaction
};

var evaluatedExpression = natspec.evaluateExpression(natspecExpression, call);
console.log(evaluatedExpression); // "Natspec evaluation failed, wrong input params"
```

If the expression contains a param unknown to the method, the output just substitutes undefined there.

``` javascript
var natspec = require('natspec');

var natspecExpression = "Will multiply `b` by 7 and return `a * 7`."; // NOTE b 
var call = {
    method: 'multiply',
    abi: abi,
    transaction: transaction
};

var evaluatedExpression = natspec.evaluateExpression(natspecExpression, call);
console.log(evaluatedExpression); // "Will multiply undefined by 7 and return 854."
```

I think in the latter case the "Natspec evaluation failed, wrong input params" could be used.
In the former, indicate explicitly that such method does not exist.

Would it not be better to have exceptions rather than encode it in the result string?

**Comment by debris** [comment]
I don't know if (and how) the exceptions can be handled by both cpp && go jsre.
Now I suggest to rename the names of messages returned, to:

```
"Natspec evaluation failed, method does not exist"
```

```
"Natspec evaluation failed, wrong input params"
```

**Comment by debris** [comment]
there are two functions now: `evaluateExpression` && `evaluateExpressionsSafe`. The difference is that safe does not throw exceptions, but return them as a result string.
